"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import AutoConfig, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Specify the path to the .env file
config = AutoConfig(search_path='aienv/config/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition
INSTALLED_APPS = [
    # django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    # basic
    'myhome',
    'accounts',
    # apps
    'data',
    'chatgpt',
    'lessons',
    'tracking',
    'wallet',
    'achievements',
    'prizes',
    # utilities
    'mail',
    'cal',
]

AUTH_USER_MODEL = 'accounts.Account'
# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.AllowAllUsersModelBackend',
#     'accounts.backends.CaseInsensitiveModelBackend',
# )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI
WSGI_APPLICATION = 'mysite.wsgi.application'
# ASGI
ASGI_APPLICATION = 'mysite.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Support switching database via environment variables
# If USE_POSTGRESQL=True or DB_NAME is provided, use PostgreSQL
# Otherwise use SQLite (default, backward compatible)
USE_POSTGRESQL = config('USE_POSTGRESQL', default=False, cast=bool)
DB_NAME = config('DB_NAME', default=None)

if USE_POSTGRESQL or DB_NAME:
    # PostgreSQL configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',  # Django 6.0+ recommends postgresql
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432', cast=int),
            'CONN_MAX_AGE': 600,  # Connection pool: keep connection for 10 minutes
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # SQLite configuration (default, backward compatible)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'media',
]
STATIC_URL = 'static/'
MEDIA_URL = 'media/'
STATIC_ROOT = BASE_DIR / 'static_cdn'
MEDIA_ROOT = BASE_DIR / 'media_cdn'

# Login Decorator
LOGIN_URL = 'accounts/signin'
LOGIN_REDIRECT_URL = 'myhome/home'
# Data and Vector DB and tmp Locations
VECTOR_DB_LOCATION = 'vector_db'
VECTOR_DB_ARCHIVE = 'vector_db_archive'
TMP_LOCATION = 'tmp'
DEFAULT_DOC_FILE = 'tmp/0/default_doc_file.txt'
# MultiMode (Data,Image,Audio,Video) Locations
CDN_DATA_LOCATION = 'cdn/data'
CDN_AUDIO_LOCATION = 'cdn/audio'
CDN_VIDEO_LOCATION = 'cdn/video'
CDN_IMAGE_LOCATION = 'cdn/image'
CDN_CHART_LOCATION = 'cdn/chart'

# Email Configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_FROM_USER = config('EMAIL_FROM_USER')
SERVER_FROM_EMAIL = config('SERVER_FROM_EMAIL')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# AI Keys
OPENAI_API_KEY = config('OPENAI_API_KEY')
GOOGLE_CSE_ID = config('GOOGLE_CSE_ID')
GOOGLE_API_KEY = config('GOOGLE_API_KEY')
TAVILY_API_KEY = config('TAVILY_API_KEY')
WOLFRAM_ALPHA_APPID = config('WOLFRAM_ALPHA_APPID')
# Default AI Settings
OPENAI = 'openai'
# OPENAI_MODEL_NAME = 'gpt-4-turbo-preview'
OPENAI_MODEL_NAME = 'gpt-3.5-turbo'
OPENAI_TEMPERATURE = 0.0
OPENAI_MAX_TOKENS = 400
VECTOR_DB = 'chroma'
SEARCH_ENGINE = 'google'
# context Window
CONTEXT_WINDOW = 10
# conversation thread identifier length
THREAD_LENGTH = 10

# Version
VERSION = '2.0'
