# Generated by Django 6.0 on 2025-12-27 02:46

import data.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVectorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_db', models.CharField(blank=True, max_length=30, null=True, verbose_name='vector db')),
                ('db_name', models.CharField(blank=True, max_length=255, null=True)),
                ('db_elements', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('doc_location', models.CharField(choices=[('local', 'local'), ('s3', 's3')], default='s3', max_length=10)),
                ('doc_file', models.FileField(blank=True, max_length=255, null=True, unique=True, upload_to=data.models.upload_path)),
                ('doc_elements', models.CharField(blank=True, max_length=255, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date posted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm', models.CharField(blank=True, max_length=30, null=True, verbose_name='llm')),
                ('llm_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='llm model')),
                ('llm_api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='llm api key')),
                ('llm_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='llm temperature')),
                ('vector_db', models.CharField(blank=True, max_length=20, null=True, verbose_name='vector db')),
                ('vector_api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='vector api key')),
                ('search_engine', models.CharField(blank=True, max_length=20, null=True, verbose_name='search_engine')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VectorDBArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('vector_db', models.CharField(blank=True, max_length=30, null=True, verbose_name='vector db')),
                ('db_name', models.CharField(blank=True, max_length=255, null=True)),
                ('db_elements', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
