# Generated by Django 6.0 on 2025-12-29 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Achievement Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Icon (emoji)')),
                ('color', models.CharField(default='#FFD700', max_length=20, verbose_name='Color (hex)')),
                ('achievement_type', models.CharField(choices=[('lesson_complete', 'Lesson Completed'), ('saving_goal_reached', 'Saving Goal Reached'), ('spending_tracked', 'Spending Tracked'), ('wallet_created', 'Wallet Created'), ('milestone', 'Milestone')], max_length=50, verbose_name='Achievement Type')),
                ('coin_reward', models.DecimalField(decimal_places=2, default=0, help_text='Virtual coins awarded when unlocked', max_digits=10, verbose_name='Coin Reward')),
                ('requirements', models.JSONField(blank=True, default=dict, help_text='JSON field for storing unlock conditions', verbose_name='Requirements')),
                ('order', models.IntegerField(default=0, help_text='Order for display', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Unlocked At')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Is Notified')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement', verbose_name='Achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]




