# Generated by Django 6.0 on 2025-12-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Prize Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='🎁', max_length=50, verbose_name='Icon (emoji)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name='Prize Image')),
                ('category', models.CharField(choices=[('digital', 'Digital Reward'), ('physical', 'Physical Prize'), ('privilege', 'Special Privilege'), ('certificate', 'Certificate')], default='digital', max_length=20, verbose_name='Category')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold_out', 'Sold Out')], default='active', max_length=20, verbose_name='Status')),
                ('coin_cost', models.DecimalField(decimal_places=2, help_text='虚拟币价格', max_digits=10, verbose_name='Coin Cost')),
                ('stock_quantity', models.IntegerField(default=-1, help_text='库存数量（-1表示无限）', verbose_name='Stock Quantity')),
                ('available_from', models.DateField(blank=True, help_text='开始可用日期', null=True, verbose_name='Available From')),
                ('available_until', models.DateField(blank=True, help_text='结束可用日期', null=True, verbose_name='Available Until')),
                ('priority', models.IntegerField(default=0, help_text='显示优先级（数字越大越靠前）', verbose_name='Priority')),
                ('is_featured', models.BooleanField(default=False, help_text='是否推荐/精选', verbose_name='Is Featured')),
                ('min_age', models.IntegerField(blank=True, null=True, verbose_name='Minimum Age')),
                ('max_age', models.IntegerField(blank=True, null=True, verbose_name='Maximum Age')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Prize',
                'verbose_name_plural': 'Prizes',
                'ordering': ['-priority', '-is_featured', 'name'],
            },
        ),
    ]
