# Generated by Django 6.0 on 2025-12-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the onboarding tour', verbose_name='Onboarding Completed'),
        ),
    ]
