# Generated by Django 6.0 on 2025-12-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_practice_mode',
            field=models.BooleanField(default=False, help_text='Whether this is a practice mode wallet', verbose_name='Is Practice Mode'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='practice_initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial balance for practice mode wallet (optional)', max_digits=10, null=True, verbose_name='Practice Initial Balance'),
        ),
    ]




