# Generated by Django 6.0 on 2025-12-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL标识')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='lessons/covers/', verbose_name='封面图片')),
                ('icon', models.CharField(default='💰', max_length=50, verbose_name='图标emoji')),
                ('lesson_number', models.IntegerField(unique=True, verbose_name='课程编号')),
                ('age_range', models.CharField(default='6-12', max_length=20, verbose_name='适合年龄')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='预计时长（分钟）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='模块标题')),
                ('section_type', models.CharField(choices=[('intro', '介绍'), ('content', '内容'), ('activity', '活动'), ('game', '游戏'), ('story', '故事'), ('summary', '总结')], default='content', max_length=20, verbose_name='模块类型')),
                ('content', models.TextField(verbose_name='内容（支持Markdown）')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/sections/', verbose_name='配图')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标emoji')),
                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lessons.lesson', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程模块',
                'verbose_name_plural': '课程模块',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='贴士标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('icon', models.CharField(default='💡', max_length=50, verbose_name='图标emoji')),
                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='lessons.lesson', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程贴士',
                'verbose_name_plural': '课程贴士',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ChatGPTDB',
        ),
    ]
