# Generated by Django 6.0 on 2025-12-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Lesson Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Lesson Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='lessons/covers/', verbose_name='Cover Image')),
                ('icon', models.CharField(default='💰', max_length=50, verbose_name='Icon (emoji)')),
                ('lesson_number', models.IntegerField(unique=True, verbose_name='Lesson Number')),
                ('age_range', models.CharField(default='6-12', max_length=20, verbose_name='Age Range')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Section Title')),
                ('section_type', models.CharField(choices=[('intro', 'Introduction'), ('content', 'Content'), ('activity', 'Activity'), ('game', 'Game'), ('story', 'Story'), ('summary', 'Summary')], default='content', max_length=20, verbose_name='Section Type')),
                ('content', models.TextField(verbose_name='Content (Markdown supported)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/sections/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (emoji)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lessons.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson Section',
                'verbose_name_plural': 'Lesson Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tip Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('icon', models.CharField(default='💡', max_length=50, verbose_name='Icon (emoji)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='lessons.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson Tip',
                'verbose_name_plural': 'Lesson Tips',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ChatGPTDB',
        ),
    ]
