# Generated by Django 6.0 on 2025-12-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_userlessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='coin_reward',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Virtual coins awarded when lesson is completed', max_digits=10, verbose_name='Coin Reward'),
        ),
    ]




