# Generated by Django 6.0 on 2025-12-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('icon', models.CharField(default='💰', max_length=50, verbose_name='Icon (emoji)')),
                ('color', models.CharField(default='#667eea', max_length=20, verbose_name='Color (hex)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Spending Category',
                'verbose_name_plural': 'Spending Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('child_name', models.CharField(blank=True, max_length=50, verbose_name='Child Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.spendingcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Spending',
                'verbose_name_plural': 'Spendings',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
