# Generated by Django 6.0 on 2025-12-29 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_init_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('child_name', models.CharField(blank=True, max_length=50, verbose_name='Child Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('goal', models.CharField(blank=True, help_text='What are you saving for?', max_length=200, verbose_name='Saving Goal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saving',
                'verbose_name_plural': 'Savings',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
