# Generated by Django 6.0 on 2025-12-29 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_saving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(help_text='What are you saving for?', max_length=200, verbose_name='Goal Name')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target Amount')),
                ('child_name', models.CharField(blank=True, max_length=50, verbose_name='Child Name')),
                ('deadline', models.DateField(blank=True, help_text='Optional deadline for this goal', null=True, verbose_name='Deadline')),
                ('icon', models.CharField(default='🎯', max_length=50, verbose_name='Icon (emoji)')),
                ('color', models.CharField(default='#28a745', max_length=20, verbose_name='Color (hex)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saving Goal',
                'verbose_name_plural': 'Saving Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='saving',
            name='saving_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings', to='tracking.savinggoal', verbose_name='Saving Goal'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='goal',
            field=models.CharField(blank=True, help_text='What are you saving for? (Deprecated: use Saving Goal instead)', max_length=200, verbose_name='Saving Goal (Legacy)'),
        ),
    ]




